[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
via_ir = true
optimizer = true
optimizer_runs = 1000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

# Test configuration
[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 100
depth = 100 